[supervisord]
nodaemon=true
pidfile=/run/supervisord.pid
user=root

[program:nginx]
command=nginx
autostart=true
autorestart=true
startsecs=5
startretries=100
redirect_stderr=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
autorstart=true
startsecs=5
startretries=100
redirect_stderr=true
