name: Docker Release

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    schedule:
        -   cron: '36 18 * * *'
    push:
        branches: [ master ]
        tags:
            - "*"
    pull_request:
        branches: [ master ]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: larvatecn/php

jobs:

    build74:

        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install cosign
                uses: sigstore/cosign-installer@1b9f7b6d8b33e3d8bdd45d340515c318619cd481
                with:
                    cosign-release: 'v1.4.0'

            -   name: Setup Docker buildx
                uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

            -   name: Log into registry ${{ env.REGISTRY }}
                uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            -   name: Build and push Docker image
                id: build-and-push
                uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
                with:
                    context: "{{defaultContext}}:7.4"
                    push: true
                    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:7,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:7.4

            -   name: Sign the published Docker image
                env:
                    COSIGN_EXPERIMENTAL: "true"
                run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}

    build80:

        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install cosign
                uses: sigstore/cosign-installer@1b9f7b6d8b33e3d8bdd45d340515c318619cd481
                with:
                    cosign-release: 'v1.4.0'

            -   name: Setup Docker buildx
                uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

            -   name: Log into registry ${{ env.REGISTRY }}
                uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            -   name: Build and push Docker image
                id: build-and-push
                uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
                with:
                    context: "{{defaultContext}}:8.0"
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:8.0

            -   name: Sign the published Docker image
                env:
                    COSIGN_EXPERIMENTAL: "true"
                run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}

    build81:

        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install cosign
                uses: sigstore/cosign-installer@1b9f7b6d8b33e3d8bdd45d340515c318619cd481
                with:
                    cosign-release: 'v1.4.0'

            -   name: Setup Docker buildx
                uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

            -   name: Log into registry ${{ env.REGISTRY }}
                uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            -   name: Build and push Docker image
                id: build-and-push
                uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
                with:
                    context: "{{defaultContext}}:8.1"
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:8.1

            -   name: Sign the published Docker image
                env:
                    COSIGN_EXPERIMENTAL: "true"
                run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}

    build82:

        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install cosign
                uses: sigstore/cosign-installer@1b9f7b6d8b33e3d8bdd45d340515c318619cd481
                with:
                    cosign-release: 'v1.4.0'

            -   name: Setup Docker buildx
                uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

            -   name: Log into registry ${{ env.REGISTRY }}
                uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract Docker metadata
                id: meta
                uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            -   name: Build and push Docker image
                id: build-and-push
                uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
                with:
                    context: "{{defaultContext}}:8.2"
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:8.2

            -   name: Sign the published Docker image
                env:
                    COSIGN_EXPERIMENTAL: "true"
                run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
