name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build PHP 7.4 Docker image
      run: cd "7.4" && docker build -t "larvatech/php:7.4" .
    - name: Build PHP 8.0 Docker image
      run: cd "8.0" && docker build -t "larvatech/php:8.0" .
